name: Deploy StreamCart Microservices

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add SSH key to agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Deploy code via SSH
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'ENDSSH'
          # Move to project directory
          cd /dotnet-microservice/stream-cart-be/
          # Pull latest code
          git pull origin main
          # Move to docker-compose directory
          cd StreamCartMicroservices/StreamCartMicroservices/
          docker-compose down
          # Build and run Docker Compose
          docker-compose up -d --build
        ENDSSH
